### ISSUE TITLE
Structx can't find type in this scope for nested structx

### ISSUE THREAD

**Issue by exellian** [exellian/rex#5]
Currently when generating nested generic Structx! types the compiler throws a "can't find the type for nested type" error. This seems a problem related to Structx. Further investigation needed

**Comment by exellian** [comment]
The structx crate works very buggy at the moment. There are two options: write a custom solution, start a issues at structx crate. hmmmm

**Comment by exellian** [comment]
So the way structx works is simply by creating a type with the name strutx_field1name_field2name_... where the field names are sorted in a lexicographic way and appended to the struct name. All types of the struct fields are simply generic type parameters. The only real problem is to generate the struct definitions somewhere global, so that the structs are the same. The way structx does this is to use a self written crate called inwelling, which collects all unique structural-records and generates a struct definition for all of them.

**Comment by exellian** [comment]
It would be so easy if these would exist: https://github.com/Centril/rfcs/blob/rfc/structural-records/text/0000-structural-records.md

**Comment by exellian** [comment]
One option would be to introduce an explicit syntax in templates, that requires every template to define its model. 
But this makes template developing way more complex for a developer.

**Comment by exellian** [comment]
Probably we could generate an extra scheme.rs file or so which stores all struct definitions of the templates. The disadvantage would be that you would have to specify a module or so to generate code from. You wouldn't be able to simply include individual template files with a macro.

**Comment by exellian** [comment]
https://github.com/oooutlk/structx/issues/2

**Comment by oooutlk** [comment]
Now structx supports nested definitions.

**Comment by exellian** [comment]
Ok so i tested it but currently nested structs don't work in every position and recursively nested structs also don't work:

Recursively nested a-structs:
```rust
pub type Props<T, T1> = Structx!{
    items: Vec<T>,
    test: usize,
    products: Structx!{
        name: T1,
        item: Structx! {
            u: usize
        }
    }
};
```
Nested a-structs wrapped in Vec<Structx!{ ... }> type:
```rust
pub type Props<T, T1> = Structx!{
    items: Vec<T>,
    test: usize,
    products: Vec<Structx!{ name: T1 }>
};
```

**Comment by exellian** [comment]
https://github.com/oooutlk/structx/issues/3
https://github.com/oooutlk/structx/issues/4

**Comment by exellian** [comment]
So finally with the commit: https://github.com/exellian/structx/commit/a2426e04f8b83e6884325f60801c429b5d94d0b0
in the structx crate, we fixed all type not found errors, because structx now supports collecting of arbitrary nested anonymous structs. We still awaiting the pr-merge into the structx crate, but for now I will close this issue
